<?php
define('IDS_NUM_COMMENTS1', 'Нет комментариев');
define('IDS_NUM_COMMENTS2', 'Комментариев: %d');
define('IDS_POSTED_BY', 'Отправлено: %name &nbsp; &#149; &nbsp; %time');
define('IDS_POSTED_TIME', 'l, Y-F-d');
define('IDS_COMMENT_BY', '%name написал(а) в %time:');
define('IDS_COMMENT_TIME', 'Y-F-d H:i:s');
define('IDS_AUTH_REMEMBER', 'Запомнить меня');
define('IDS_AUTH_EMAIL', 'Ваш email');
define('IDS_AUTH_PASSWORD', 'Ваш пароль');
define('IDS_AUTH_WELCOME1', 'Приветствуем, %name (<a href=%logout>Выйти</a> | <a href=%post>Новое сообщение</a> | <a href=%account>Мой аккаунт</a>)');
define('IDS_AUTH_WELCOME2', 'Приветствуем, anonymous (<a href=%link>Войти</a>)');
define('IDS_LOGGED_IN', 'Вход выполнен');
define('IDS_MUST_LOGIN', 'Для отправки сообщений надо ВОЙТИ в систему');
define('IDS_EMPTY_HEADER', 'Заголовок не должен быть пустым');
define('IDS_EMPTY_BODY', 'Сообщение не должно быть пустым');
define('IDS_UNKNOWN_USER', 'Неизвестный пользователь');
define('IDS_NO_USER_INFO', '<i>Информация о пользователе недоступна</i>');
define('IDS_AUTH_ERROR', 'Authentication error');
define('IDS_USER_POSTS', 'Posts, made by %s');
define('IDS_NEW_POST_OK', 'Ваш пост успешно сохранен. <a href=%s>Нажмите сюда</a> чтобы прочитать его.');
define('IDS_POST_OK', 'Ваш комментарий успешно сохранен');
define('IDS_NEXT_PAGE', 'Следующая страница');
define('IDS_PREV_PAGE', 'Предыдущая страница');
define('IDS_PAGES1', 'Станицы: ');
define('IDS_PAGES2', '');
define('IDS_BAD_EMAIL', 'Email address is not valid');
define('IDS_EMAIL_EXISTS', 'The email already exists in database. Please use password reminder form below in order to get your password.');
define('IDS_REGISTRATION_OK', 'Регистрационные данные были Вам успешно отправлены.');
define('IDS_SENDMAIL_ERROR', 'Ошибка отправки почты.');
define('IDS_SENDMAIL_OK', 'Письмо успешно отправлено.');
define('IDS_DEFAULT_NAME', 'Подписчик');
define('IDS_EMAIL_NOT_FOUND', 'The email address is not found in the database');
define('IDS_ALL_REQ', 'All fields are required!');
define('IDS_PASSW_NOT_MATCH', 'Новый пароль не совпадает');
define('IDS_USER_NOT_FOUND', 'Specified email and password is not found in the database');
define('IDS_PASSWORD_CHANGED', 'Паротль успешно обновлен.');
define('IDS_URL_POSTING_DENIED', '#');
define('IDS_POSTING_DENIED', 'Вы не можете добавлять новые сообщения.');
define('IDS_INFO_SAVED', 'Информация обновлена.');
define('IDS_ADMIN_EDIT', 'Редактировать');
define('IDS_ADMIN_DELETE', 'Удалить');
define('IDS_ADMIN_BAN', 'Ban user');
define('IDS_MONTHS', 'Январь Февраль Март Апрель Май Июнь Июль Август Сентябрь Октябрь Ноябрь Декабрь');
define('IDS_DAYSOFWEEK', 'Вс Пн Вт Ср Чт Пт Сб');
define('IDS_LOW_RIGHTS', 'У ВАс недостаточно прав для этого действия');
define('IDS_BAN_USER_CONFIRM', 'Are you sure you want to ban the user and delete all his messages and comments?\n\nThere will be no undo for this action!');
define('IDS_DEL_COM_CONFIRM', 'Are you sure you want to delete the comment?\n\nThere will be no undo for this action!');
define('IDS_DEL_MSG_CONFIRM', 'Are you sure you want to delete the message and ALL comments?\n\nThere will be no undo for this action!');
define('IDS_DELETE_OTHER', 'You may not delete messages of other users.');
define('IDS_DELETE_OK', 'Сообщение успешно удалено.');
define('IDS_DELETE_ERROR', 'The message does not exist!');
define('IDS_MSG_NOT_EXISTS', 'Topic does not exist!');
define('IDS_BAN_YOURSELF', 'You can not ban yourself');
define('IDS_USER_BAN_OK', 'User successfully banned.<br>All his messages are removed from database.');
define('IDS_RSS_COMMENTS', 'Подписаться на комментарии к этому сообщению');
define('IDS_RSS_USER', 'Подписаться на сообщения пользователя');
define('IDS_TAG1', 'HTML tag problem at the begining of text (">" is unexpected)');
define('IDS_TAG2', 'HTML tag not closed at the end of a text (">" is expected, but not found)');
define('IDS_TAG3', 'HTML tag not closed ("<TAG" without corresponding ">" character)');
define('IDS_TAG4', '">" is unsexpected');
define('IDS_TAG5', 'Closed tag "</%s>" found without corresponding opened one');
define('IDS_TAG6', 'Tag "<%s>" is not allowed!');
define('IDS_READ_MORE', 'read more');
?>
